name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "SANTA BRING YOU GIFT FOR CONTRIBUTING +10 SOCIAL CREDITZ"
        pr-message: "damn bro you spent time on this? +100 social creditz"
